version: '3.1'
services:
  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./registers-data.js:/docker-entrypoint-initdb.d/registers-data.js
    environment:
      - MONGO_INITDB_DATABASE=company_registers
