management.health.mongodb.enabled=false
management.endpoints.access.default=read_only
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never

management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics

chs.kafka.api.endpoint=${CHS_KAFKA_API_URL:localhost}
chs.kafka.api.key=${CHS_API_KEY:chsApiKey}

spring.mongodb.uri=${MONGODB_URL:mongodb://mongo:27017}/company_registers?retryWrites=false
spring.data.mongodb.name=company_registers
spring.jackson.default-property-inclusion=NON_NULL
